# Generated by Django 3.2.3 on 2021-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_text', models.TextField()),
                ('main_text', models.TextField()),
                ('line_text', models.TextField()),
                ('download_link', models.FileField(upload_to='files/download_links/%Y/%m/%d/')),
            ],
        ),
    ]
