# Generated by Django 3.2.3 on 2021-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='background',
            field=models.ImageField(default='image.jpeg', upload_to='files/background/%Y/%m/%d/'),
        ),
    ]
