# Generated by Django 3.2.3 on 2021-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile',
            field=models.ImageField(default=0, upload_to='images/profiles/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
