# Generated by Django 3.2.3 on 2021-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
