# Generated by Django 3.2.3 on 2021-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_art_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Art',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
